_BASE_: configs_vid/youtubevis_2021/swin/video_maskformer2_swin_tiny_bs16_8ep.yaml
MODEL:
  WEIGHTS: "moby_swin_t_300ep_pretrained.pth"
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 11
  RESNETS:
    DEPTH: 18
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  BASE_LR: 0.00003
  WARMUP_FACTOR: 1e-6
  WARMUP_ITERS: 5000
  WEIGHT_DECAY: 0.01
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_EMBED: 0.0
  BACKBONE_MULTIPLIER: 1.0
  IMS_PER_BATCH: 4
  MAX_ITER: 500000
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS:
    - 200000
    - 400000
  CHECKPOINT_PERIOD: 10000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  SAMPLING_FRAME_NUM: 2
VERSION: 2
SEED: 42
OUTPUT_BASEDIR: '../outputs/'
FLAGS:
  CCROP: False
UNSUPVIDSEG:
  DATASET: 'KITTI'
  FLOW_LIM: 30
  RESOLUTION: 
    - 288
    - 960
  LOSS_DISP_THRESH: 0.1
  LOSS_EQUIV: 'const(1.0)'
